### ISSUE TITLE
彈幕下載失敗

### ISSUE THREAD

**Issue by MRLlllling** [RyanL-29/aniGamerPlus#16]
## 問題描述
[Errno 2] No such file or directory: 'C:\\Users\\georg\\AppData\\Local\\Temp\\_MEI20202\\DanmuTemplate.ass'

## 錯誤截圖
![image](https://user-images.githubusercontent.com/64152726/161984575-c8580108-f8e9-45b1-946d-3ea4300d289b.png)

## config.json 配置
{
    "bangumi_dir": "D:\\test",
    "temp_dir": "D:\\test",
    "classify_bangumi": true,
    "check_frequency": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_bangumi_name_to_video_meta": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36 SE 2.X MetaSr 1.0",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": true,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 3,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 16,
    "database_version": 2.0
}

## sn_list.txt 配置
無 手動下發的

2022-04-06 21:06:46 收到新cookie: sn=28628	
2022-04-06 21:06:46 用戶cookie刷新 ANIME_SIGN : sn=28628	
2022-04-06 21:06:47 正在等待: sn=28628	《進擊的巨人 The Final Season [28]》 由於不是VIP賬戶, 正在等待25s廣告時間
2022-04-06 21:06:47 正在等待: sn=28628	《進擊的巨人 The Final Season [28]》 由於不是VIP賬戶, 正在等待25s廣告時間
2022-04-06 21:06:47 收到新cookie: sn=28628	
2022-04-06 21:06:47 用戶cookie刷新 ANIME_SIGN : sn=28628	
2022-04-06 21:06:47 正在等待: sn=28628	《進擊的巨人 The Final Season [28]》 由於不是VIP賬戶, 正在等待25s廣告時間
2022-04-06 21:06:49 正在等待: sn=28628	《進擊的巨人 The Final Season [28]》 由於不是VIP賬戶, 正在等待25s廣告時間
2022-04-06 21:06:58 檢查更新 檢查更新成功
2022-04-06 21:06:58 自動模式啓動aniGamerPlus 當前aniGamerPlus版本: aniGamerPlus_v23.2_ryan_fork_windows_64bit 
2022-04-06 21:06:58 工作目錄: C:\Users\georg\Downloads\aniGamerPlus_v23.2_ryan_fork_windows_64bit 
2022-04-06 21:07:02 Web控制面板已啓動 訪問地址: http://127.0.0.1:5000
2022-04-06 21:07:02 開始更新 
2022-04-06 21:07:02 讀取cookie 發現cookie檔案
2022-04-06 21:07:02 讀取cookie 已讀取cookie
2022-04-06 21:07:02 更新資訊 本次更新添加了 0 個新任務, 目前列隊中共有 0 個任務
2022-04-06 21:07:02 更新终了 
2022-04-06 21:07:20 Dashboard 通過 Web 控制臺下達了手動任務
2022-04-06 21:07:20 解析模式: sn=28628	Web解析
2022-04-06 21:07:21 收到新cookie: sn=28628	
2022-04-06 21:07:21 用戶cookie刷新 ANIME_SIGN : sn=28628	
2022-04-06 21:07:23 正在等待: sn=28628	《進擊的巨人 The Final Season [28]》 由於不是VIP賬戶, 正在等待25s廣告時間
2022-04-06 21:07:49 任務狀態: sn=28628	指定清晰度不存在, 選取最近可用清晰度: 720P
2022-04-06 21:07:50 正在下載: sn=28628	【動畫瘋】進擊的巨人 The Final Season[28][720P].mp4 title=進擊的巨人 The Final Season [28]
2022-04-06 21:08:24 下載狀態: sn=28628	【動畫瘋】進擊的巨人 The Final Season[28][720P].mp4 下載完成, 正在解密合并……
2022-04-06 21:08:27 下載狀態: sn=28628	【動畫瘋】進擊的巨人 The Final Season[28][720P].mp4 解密合并完成, 本集 233MB, 正在移至番劇目錄……
2022-04-06 21:08:27 下載完成: sn=28628	【動畫瘋】進擊的巨人 The Final Season[28][720P].mp4
2022-04-06 21:08:29 下載異常: sn=28628	發生未知異常: [Errno 2] No such file or directory: 'C:\\Users\\georg\\AppData\\Local\\Temp\\_MEI174962\\DanmuTemplate.ass'
2022-04-06 21:08:29 下載異常: sn=28628	異常詳情:
Traceback (most recent call last):
  File "aniGamerPlus.py", line 343, in __download_only
  File "Anime.py", line 926, in download
  File "Danmu.py", line 68, in download
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\georg\\AppData\\Local\\Temp\\_MEI174962\\DanmuTemplate.ass'

**Comment by MRLlllling** [comment]
我覺得是不是這個彈幕模板文件路徑有問題？

**Comment by RyanL-29** [comment]
你是用原始碼啟動還是.exe ?

**Comment by RyanL-29** [comment]
可以試一下 [aniGamerPlus_v23.3_ryan_fork_windows_64bit](https://github.com/RyanL-29/aniGamerPlus/releases/tag/aniGamerPlus_v23.3_ryan_fork_windows_64bit)

**Comment by MRLlllling** [comment]
這一版本是OK的 多謝
