### ISSUE TITLE
抓取失敗

### ISSUE THREAD

**Issue by skylimiter** [RyanL-29/aniGamerPlus#23]
## 问题描述
#在这里详细说明你遇到了什么问题#
无法下载

## 错误截图
[https://i.imgur.com/MZ63ix3.png](https://i.imgur.com/MZ63ix3.png)
#在这里附上错误的窗口截图#

## config.json 配置
```
{
    "bangumi_dir": "",
    "temp_dir": "",
    "classify_bangumi": true,
    "classify_season": false,
    "check_frequency": 5,
    "download_cd": 60,
    "parse_sn_cd": 5,
    "download_resolution": "1080",
    "lock_resolution": false,
    "only_use_vip": false,
    "default_download_mode": "latest",
    "use_copyfile_method": false,
    "multi-thread": 1,
    "multi_upload": 3,
    "segment_download_mode": true,
    "multi_downloading_segment": 2,
    "segment_max_retry": 8,
    "add_bangumi_name_to_video_filename": true,
    "add_bangumi_name_to_video_meta": true,
    "add_resolution_to_video_filename": true,
    "customized_video_filename_prefix": "【動畫瘋】",
    "customized_bangumi_name_suffix": "",
    "customized_video_filename_suffix": "",
    "video_filename_extension": "mp4",
    "zerofill": 1,
    "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36",
    "use_proxy": false,
    "proxy": "http://user:passwd@example.com:1000",
    "no_proxy_akamai": false,
    "upload_to_server": false,
    "ftp": {
        "server": "",
        "port": "",
        "user": "",
        "pwd": "",
        "tls": true,
        "cwd": "",
        "show_error_detail": false,
        "max_retry_num": 15
    },
    "user_command": "shutdown -s -t 60",
    "coolq_notify": false,
    "coolq_settings": {
        "msg_argument_name": "message",
        "message_suffix": "追加的資訊",
        "query": [
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=12345678",
            "http://127.0.0.1:5700/send_group_msg?access_token=abc&group_id=87654321"
        ]
    },
    "telebot_notify": false,
    "telebot_token": "",
    "telebot_use_chat_id": false,
    "telebot_chat_id": "",
    "discord_notify": false,
    "discord_token": "",
    "plex_refresh": false,
    "plex_url": "",
    "plex_token": "",
    "plex_section": "",
    "plex_naming": false,
    "faststart_movflags": false,
    "audio_language": false,
    "use_mobile_api": false,
    "danmu": false,
    "danmu_ban_words": [],
    "check_latest_version": true,
    "read_sn_list_when_checking_update": true,
    "read_config_when_checking_update": true,
    "ads_time": 25,
    "mobile_ads_time": 25,
    "use_dashboard": true,
    "dashboard": {
        "host": "127.0.0.1",
        "port": 5000,
        "SSL": false,
        "BasicAuth": false,
        "username": "admin",
        "password": "admin"
    },
    "save_logs": true,
    "quantity_of_logs": 7,
    "config_version": 16.3,
    "database_version": 2.0
}
```

## log
```
2023-09-29 20:01:33 Dashboard 通过 Web 控制台下达了手动任务
当前下载模式: 仅下载本集

2023-09-29 20:01:33 SN 解析冷却 5 秒
2023-09-29 20:01:39 开始下载: sn=35368  《天地无用！GXP 乐园始动编 [5] [特别篇]》 识别到VIP账户, 立即下载
2023-09-29 20:01:39 正在下载: sn=35368  【动画疯】天地无用！GXP 乐园始动编 [特别篇] - 5 [1080P].mp4 title=天地无用！GXP 乐园始动编 [5] [特别篇]
2023-09-29 20:01:50 下载状态: sn=35368  【动画疯】天地无用！GXP 乐园始动编 [特别篇] - 5 [1080P].mp4 下载完成, 正在解密合并……
2023-09-29 20:01:50 下载异常: sn=35368  发生未知异常: [WinError 2] 系统找不到指定的档案。: 'C:\\Users\\AKito\\Desktop\\a2\\temp\\【动画疯】天地无用！GXP 乐园始动编 [特别篇] - 5 [1080P].MERGING.mp4'
2023-09-29 20:01:50 任务失败: sn=35368  title=天地无用！GXP 乐园始动编 [5] [特别篇] 10s后自动重启,最多重试三次
Exception in thread Thread-9:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "Dashboard\Server.py", line 152, in run_cui
    cui(data['sn'], resolution, mode, thread_limit, [], classify=data['classify'], realtime_show=False, cui_danmu=data['danmu'])
  File "aniGamerPlus.py", line 507, in __cui
  File "aniGamerPlus.py", line 426, in __download_only
  File "Anime.py", line 110, in renew
  File "Anime.py", line 233, in __get_episode_list
IndexError: list index out of range
```

**最好上传 log 档案**

**Comment by RyanL-29** [comment]
不好意思, 我無法重現這個問題...
想問一下你在下載中有刪除過 a2\\temp\\ 這個資料夾嗎?

**Comment by RyanL-29** [comment]
由於沒有回復, 此問題將會暫時被關閉
